---
title: "Cote Paris Nantes"
output: html_document
---

# Etablir une cote de retard sur la liaison Paris-Nantes

```{r}
library(dplyr)
Paris_Nantes_modiff <- Paris_Nantes %>% 
  mutate(prop_trains_en_retard = Nombre.trains.en.retard...15min/Nombre.de.circulations.prévues) %>% 
  select(Année, Mois, Nombre.de.circulations.prévues, Nombre.trains.en.retard...15min, prop_trains_en_retard)
proba_Paris_Nantes <- sum(Paris_Nantes_modiff$prop_trains_en_retard)/44
cote_Paris_Nantes <- 1/proba_Paris_Nantes
cote_Paris_Nantes
count(Paris_Nantes_modiff)
```



# Etablir la cote de toute les liaisons

```{r}
SNCF_regularite <- read.csv2("regularite-mensuelle-tgv-aqst.csv")
SNCF_regularite_cote <- SNCF_regularite %>% 
  select(Année,Mois,Gare.de.départ,Gare.d.arrivée, Durée.moyenne.du.trajet..min., Nombre.de.circulations.prévues, Nombre.de.trains.annulés, Nombre.de.trains.en.retard.à.l.arrivée, Nombre.trains.en.retard...15min, Nombre.trains.en.retard...30min, Nombre.trains.en.retard...60min) %>% 
  mutate(Gare.d.arrivée = as.character(Gare.d.arrivée),
         Gare.de.départ = as.character(Gare.de.départ),
         Mois = as.character(Mois)) %>% 
  mutate_if(is.factor, funs(as.numeric(levels(.)[.]))) %>% 
  group_by(Gare.d.arrivée, Gare.de.départ) %>% 
  mutate(prop_trains_en_retard = Nombre.trains.en.retard...15min/Nombre.de.circulations.prévues)

count <- count(SNCF_regularite_cote)

sum_prop_by_line <- SNCF_regularite_cote %>%
  summarise(sum_prop=sum(prop_trains_en_retard))
   
Cotes <- full_join(count, sum_prop_by_line, by = c("Gare.de.départ", "Gare.d.arrivée")) %>% 
  mutate(cote = n/sum_prop) %>% 
  select(-n, -sum_prop)
  
Cotes

```

