globalVariables(c("annee", "mois", "sevice", "gare_de_depart", "gare_d_arrivee", "duree_moyenne_du_trajet",
                    "nombre_de_circulations_prevues", "nombre_de_trains_annules", "commentaire_facultatif_annulations",
                    "nombre_de_trains_en_retard_au_depart", "retard_moyen_des_trains_en_retard_au_depart",
                    "retard_moyen_de_tous_les_trains_au_depart", "commentaire_facultatif_retards_au_depart",
                    "nombre_de_trains_en_retard_a_l_arrivee", "retard_moyen_des_trains_en_retard_a_l_arrivee",
                    "retard_moyen_de_tous_les_trains_a_l_arrivee", "commentaire_facultatif_retards_a_l_arrivee",
                    "trains_en_retard_pour_causes_externes",
                    "trains_en_retard_a_cause_infrastructure_ferroviaire",
                    "trains_en_retard_a_cause_gestion_trafic",
                    "trains_en_retard_a_cause_materiel_roulant",
                    "trains_en_retard_a_cause_gestion_en_gare_et_reutilisation_de_materiel",
                    "trains_en_retard_a_cause_prise_en_compte_voyageurs",
                    "nombre_trains_en_retard_15min","retard_moyen_trains_en_retard_15min",
                    "nombre_trains_en_retard_30min","nombre_trains_en_retard_60min",
                    "periode","retard_pour_causes_externes","retard_a_cause_infrastructure_ferroviaire",
                    "retard_a_cause_gestion_trafic","retard_a_cause_materiel_roulant",
                    "retard_a_cause_gestion_en_gare_et_reutilisation_de_materiel","retard_a_cause_prise_en_compte_voyageurs",
                  "proportion_de_trains_en_retard", "cote_tbl", "country_arrivee", "CODE_DEPT", "cote", "departement"))
