---
title: "Trainspack Vignette"
author: "Tristan Mayer"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

#Trainpack Vignette

## Introduction
The idea of our package is to design the functions that will feed our shiny application.
We produced an application on which people can bet on the delay of their train.
Inspired by the sports betting websites (betfair, pmu, winamax ...), we created a simple display where someone can bet on the delay of a train. We also wanted to display some facts and useful data to help the bettor placing his/her bet.
Therefore, the main page of our application will be a simple menu to choose the train on which to bet. Once chosen, the odds are displayed with some facts that might influence the probability of the train to be late. There is also a space where to put the amount of money to bet. Once confirmed, the potential gain is displayed.


To build this package, we started from the train data from the open data website of the SNCF. Unfortunately, we only have access to the monthly data of every TGV line and not the detail of all the trains. We met the SNCF head of data at a forum in Paris in october and asked him whether it was possible to recover this kind of data for all the trains but it is not yet possible so we adapted our calculations and functions accordingly.
We cleaned the dataset to remove the points and the accent form the column name in order to be able to put it on github and export it in other countries. 


"""add description of the cleaning of the dataset"



Given this dataset, we first needed a function that will return the odds of the train to be late. To identify the train, the easiest characterisitcs where the station of departure and arrival, and the month of the travel. The function is very simple but easily complexifiable: the idea was to build something simple and maybe complexify, affine our predictions of the probability of a specific train to arrive late in the future. To do this, the only thing to modify in the entire package would be the function "fonction_cote".
Then we needed other functions that would be able to identify the train selected and provide the related data about the usual reasons for its delays, its average delay over the last 3 years, the number of articles mentionning the words "grève sncf" on LeMonde.fr during the last month, the map of the trip, the average delay in the departement of arrival ...
ALl those facts are included in diagrams on the appliaction and allows to inform the bettor.

Finally we added another small function called "ypep" just for fun. 
